version: "3"

services:
  server:
    container_name: server
    restart: always
    build: 
      context: .
      dockerfile: "Dockerfile.development"
    ports:
      - "5000:5000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none